name: Playground

on:
  push:
    branches: [ "work" ]

env:
  YAGNA_VERSION: 0.17.1

jobs:
  playground:
    name: Test playground
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Maximum run time for the job

    steps:
      - uses: actions/checkout@v4

      - name: Start centralnet
        run: |
          docker run -p 7999:7999 -d scx1332/centralnet ya-sb-router -l tcp://0.0.0.0:7999

      - name: Install yagna
        run: |
          curl -sSf https://join.golem.network/as-provider --output as-provider.sh
          chmod +x as-provider.sh
          ./as-provider.sh
        env:
          GOLEM_ACCEPT_TOS: yes
          BATCH_MODE: yes
          YA_INSTALLER_CORE: ${{ env.YAGNA_VERSION }}
